### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DavidEichmann** [DavidEichmann/alpaca-netcode#1]
* [ ] **Snapshots** when players join, ideally they'd just get a snapshot of the current state rather than resimulating form tick 0. We could still avoid simulating on the server by having clients send the serialized state to the server. Some trust is needed, but we could e.g. request the full state from one client and a hash from others to check.
* [ ] I'm working on a deterministic Float type that I should publish and support in alpaca-netcode
* [ ] Take game time and/or delta time (using deterministic float) instead of tick for game step function
* [ ] Better control over players joining. Currently any one can join at any
  time.
* [ ] Cleaner shutdown. At the moment there isn't a clear end to the game or
  even to a player leaving. The server just uses a timeout on not receiving
  messages from a client.
* [ ] Expose clock synchronization settings in `ClientConfig`
* [ ] Custom input prediction via a `input -> input` parameter.
* [ ] Logging and Metrics e.g. ping, bandwidth, packet loss, jitter.
* [ ] Audit / time traveling debug
* [ ] Client Disconnect message
* [ ] Benchmarks
* [ ] Better tests
